language: ruby
rvm:
  - '2.0.0'
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - ruby-head
  - jruby-9.1.5.0
script: bundle exec rspec && if [ -d coverage ]; then bundle exec codeclimate-test-reporter; fi
