# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{libravatar}
  s.version = "1.2.0"

  s.authors = ["Kang-min Liu"]
  s.date = %q{2011-07-24}
  s.description = %q{libravatar.org provides avatar image hosting (like gravatar.com). Their users may associate avatar images with email or openid. This rubygem can be used to generate libravatar avatar image URL}
  s.email = %q{gugod@gugod.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/libravatar.rb",
    "libravatar.gemspec",
    "test/helper.rb",
    "test/test_libravatar.rb"
  ]
  s.homepage = %q{http://github.com/gugod/libravatar}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Avatar URL Generation wih libravatar.org}

  s.required_ruby_version = '>= 1.9.3'

  s.add_development_dependency 'shoulda', '> 1.2.3'
  s.add_development_dependency 'jeweler'

  s.add_development_dependency 'bundler', '~> 1.6'
  s.add_development_dependency 'rake'
end

