# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: vishnu 1.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "vishnu"
  s.version = "1.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Anton Smirnov", "Kang-min Liu"]
  s.date = "2016-06-20"
  s.description = "libravatar.org provides avatar image hosting (like gravatar.com). Their users may associate avatar images with email or openid. This rubygem can be used to generate libravatar avatar image URL"
  s.email = "sandfox@sandfox.me"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/libravatar.rb",
    "lib/vishnu.rb",
    "test/helper.rb",
    "test/test_libravatar.rb",
    "vishnu.gemspec"
  ]
  s.homepage = "http://github.com/sandfoxme/vishnu"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Avatar URL Generation wih libravatar.org"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, ["> 1.2.3"])
      s.add_development_dependency(%q<minitest>, ["= 4.7.5"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<shoulda>, ["> 1.2.3"])
      s.add_dependency(%q<minitest>, ["= 4.7.5"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<shoulda>, ["> 1.2.3"])
    s.add_dependency(%q<minitest>, ["= 4.7.5"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

